### Simple Chat
POST http://localhost:11434/v1/chat/completions
Content-Type: application/json

{
  "model": "gemma3:1b",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ]
}

### Tool Instruction
POST http://localhost:11434/v1/chat/completions
Content-Type: application/json

{
  "model": "gemma3:1b",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant with access to the bash cli. Run a command using messages like <bash>ls -la</bash>, always wrapping the desired command in the xml tag. For example: send <bash>pwd</bash> to print the current working directory. It is VERY important that YOU DO wrap your command in the xml tag and do not include any other text."
    },
    {
      "role": "user",
      "content": "What's the left space on my disk?"
    }
  ]
}
